### ISSUE TITLE
password.txt not found

### ISSUE THREAD

**Issue by jlazerus** [2016SoftwarePractices/Encryptomail#44]
I pulled from git this morning and I can't start a server because of this error. Can anyone write an instruction about how to resolve this? Thanks!
`Message from application: No such file or directory @ rb_sysopen - password.txt (Errno::ENOENT)
  /Users/jlazerus/GitHub/Encryptomail/webapp/config/environment.rb:8:in `initialize'
  /Users/jlazerus/GitHub/Encryptomail/webapp/config/environment.rb:8:in `new'
  /Users/jlazerus/GitHub/Encryptomail/webapp/config/environment.rb:8:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /Users/jlazerus/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /Users/jlazerus/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /Users/jlazerus/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /Users/jlazerus/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /Users/jlazerus/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /Users/jlazerus/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /Users/jlazerus/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.26/src/helper-scripts/rack-preloader.rb:29:in `<main>'`

**Comment by jlazerus** [comment]
password.txt goes in webapp directory.
